<a href="https://colab.research.google.com/github/prasannaas138-alt/youtube-recommendation-system/blob/main/Youtube_Recommendation_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/content/youtube_videos.csv')

In [3]:
df.shape

(5000, 8)

In [4]:
df.head()

,video_id,title,category,description,tags,channel,views,likes
0,V03407,SQL for Beginners Explained for Beginners,SQL,This video breaks down sql for beginners into ...,"indexing, database, sql, sql for beginners, jo...",Quantum Coders,837156,19218
1,V00758,Data Science Projects Best Practices,Data Science,"In this tutorial, we explore data science proj...","dataset, data, insights, tutorial, statistics,...",PeakProductivity,43330,3875
2,V03625,Mastering Building Scalable Cloud Applications...,Cloud Computing,We take a deep dive into building scalable clo...,"howto, cloud computing, virtual machines, buil...",LearnWithCode,298869,27734
3,V04545,Self-Taught Developer Roadmap Made Simple,Education,This video breaks down self-taught developer r...,"study tips, skill building, self-improvement, ...",FutureTech Studio,271653,18951
4,V03236,Node.js Basics Deep Dive,Node.js,"We take a deep dive into node.js basics, cover...","node.js, api, html, express, walkthrough, node...",Quantum Coders,5392,337


In [5]:
df.columns

Index(['video_id', 'title', 'category', 'description', 'tags', 'channel',
       'views', 'likes'],
      dtype='object')

In [6]:
df.isnull().sum()

,0
video_id,0
title,0
category,0
description,0
tags,0
channel,0
views,0
likes,0


In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df['video_id'].nunique()

5000

In [9]:
df['category'].nunique()

30

In [10]:
df['category'].value_counts()

,count
category,
Python,405
Data Science,380
Machine Learning,380
Web Development,287
Artificial Intelligence,253
Deep Learning,220
Programming,203
Generative AI,177
React,177


In [11]:
df[['views','likes']].describe()

,views,likes
count,5.000000e+03,5000.000000
mean,1.392694e+05,8825.077400
std,3.873113e+05,27051.189948
min,1.000000e+03,14.000000
25%,1.242675e+04,670.000000
50%,3.706800e+04,2061.000000
75%,1.107460e+05,6508.500000
max,6.000000e+06,698788.000000


In [12]:
text_columns = ['title','description','tags','category']

for column in text_columns:
  df[column] = df[column].fillna("").astype(str)

In [13]:
df['combined_text'] = (
    df['title'] + " " +
    df['description'] + " " +
    df['tags'] + " " +
    df['category']
)

In [14]:
df[['title' , 'combined_text']].head()

,title,combined_text
0,SQL for Beginners Explained for Beginners,SQL for Beginners Explained for Beginners This...
1,Data Science Projects Best Practices,Data Science Projects Best Practices In this t...
2,Mastering Building Scalable Cloud Applications...,Mastering Building Scalable Cloud Applications...
3,Self-Taught Developer Roadmap Made Simple,Self-Taught Developer Roadmap Made Simple This...
4,Node.js Basics Deep Dive,Node.js Basics Deep Dive We take a deep dive i...


In [15]:
df[['video_id' , 'title' , 'combined_text']].head()

,video_id,title,combined_text
0,V03407,SQL for Beginners Explained for Beginners,SQL for Beginners Explained for Beginners This...
1,V00758,Data Science Projects Best Practices,Data Science Projects Best Practices In this t...
2,V03625,Mastering Building Scalable Cloud Applications...,Mastering Building Scalable Cloud Applications...
3,V04545,Self-Taught Developer Roadmap Made Simple,Self-Taught Developer Roadmap Made Simple This...
4,V03236,Node.js Basics Deep Dive,Node.js Basics Deep Dive We take a deep dive i...


In [16]:
df['combined_text'].dtype

dtype('O')

In [17]:
df['combined_text'] = df['combined_text'].str.lower()

In [18]:
df['combined_text'] = df['combined_text'].str.replace(r"\s+" , " " , regex = True).str.strip()

In [19]:
df[['title' , 'combined_text']].head()

,title,combined_text
0,SQL for Beginners Explained for Beginners,sql for beginners explained for beginners this...
1,Data Science Projects Best Practices,data science projects best practices in this t...
2,Mastering Building Scalable Cloud Applications...,mastering building scalable cloud applications...
3,Self-Taught Developer Roadmap Made Simple,self-taught developer roadmap made simple this...
4,Node.js Basics Deep Dive,node.js basics deep dive we take a deep dive i...


In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()

tfidf_matrix = tfidf.fit_transform(df['combined_text'])

In [21]:
tfidf_matrix.shape

(5000, 586)

In [22]:
tfidf.get_feature_names_out()

array(['2024', 'able', 'absolute', 'accuracy', 'acing', 'activation',
       'advanced', 'adversarial', 'agents', 'aggregate', 'ai',
       'algorithm', 'algorithms', 'along', 'also', 'an', 'analysis',
       'and', 'animations', 'any', 'anyone', 'api', 'app', 'application',
       'applications', 'applies', 'apply', 'apps', 'array', 'artificial',
       'as', 'async', 'asynchronous', 'at', 'attacks', 'augmented',
       'authentication', 'autoencoders', 'automation', 'avoid', 'await',
       'away', 'aws', 'azure', 'backend', 'backpropagation', 'balance',
       'basics', 'be', 'beat', 'beats', 'beginner', 'beginners', 'best',
       'better', 'bias', 'big', 'boosting', 'branching', 'breaks',
       'browser', 'build', 'building', 'business', 'by', 'camera', 'can',
       'cardio', 'career', 'careers', 'case', 'cases', 'cd', 'change',
       'changing', 'chatbot', 'chatbots', 'ci', 'classes',
       'classification', 'classifier', 'clean', 'cleaning', 'clear',
       'client', 'closur

In [23]:
len(tfidf.get_feature_names_out())

586

In [24]:
tfidf.get_feature_names_out()[:50]

array(['2024', 'able', 'absolute', 'accuracy', 'acing', 'activation',
       'advanced', 'adversarial', 'agents', 'aggregate', 'ai',
       'algorithm', 'algorithms', 'along', 'also', 'an', 'analysis',
       'and', 'animations', 'any', 'anyone', 'api', 'app', 'application',
       'applications', 'applies', 'apply', 'apps', 'array', 'artificial',
       'as', 'async', 'asynchronous', 'at', 'attacks', 'augmented',
       'authentication', 'autoencoders', 'automation', 'avoid', 'await',
       'away', 'aws', 'azure', 'backend', 'backpropagation', 'balance',
       'basics', 'be', 'beat'], dtype=object)

In [25]:
from sklearn.metrics.pairwise import cosine_similarity

In [28]:
similarity_matrix = cosine_similarity(tfidf_matrix)

In [29]:
similarity_matrix.shape

(5000, 5000)

In [30]:
similarity_matrix[:5 , :5]

array([[1.        , 0.03615233, 0.03439448, 0.08720232, 0.04138664],
       [0.03615233, 1.        , 0.10858245, 0.01940422, 0.02963238],
       [0.03439448, 0.10858245, 1.        , 0.03277798, 0.08400248],
       [0.08720232, 0.01940422, 0.03277798, 1.        , 0.02371873],
       [0.04138664, 0.02963238, 0.08400248, 0.02371873, 1.        ]])

In [31]:
similarity_scores = similarity_matrix[0]

In [32]:
similarity_scores.argsort()

array([ 537, 2221, 4146, ..., 4122, 4036,    0])

In [33]:
similarity_scores.argsort()[::-1]

array([   0, 4036, 4122, ..., 4146, 2221,  537])

In [34]:
similar_indeces = similarity_scores.argsort()[::-1][:6]

In [36]:
df.iloc[similar_indeces][['video_id' , 'title' , 'category']]

,video_id,title,category
0,V03407,SQL for Beginners Explained for Beginners,SQL
4036,V03389,SQL for Beginners Best Practices,SQL
4122,V03305,SQL for Beginners Tips and Tricks,SQL
1897,V03373,Complete SQL for Data Analysis Tutorial,SQL
3267,V03433,SQL for Beginners Deep Dive,SQL
430,V03330,SQL for Beginners Project Walkthrough,SQL


In [52]:
def recommend_video (title , n=5):
  index = df[df['title'] == title].index[0]

  similarity_scores = similarity_matrix[index]

  similarity_indices = similarity_scores.argsort()[::-1][1:n+1]

  recommendation = df.iloc[similarity_indices].copy()

  recommendation['similarity_score'] = similarity_scores[similarity_indices]

  return recommendation[
      ['video_id' , 'title' , 'category' , 'channel' , 'similarity_score']
  ]


In [53]:
df['title'].head(10)

,title
0,SQL for Beginners Explained for Beginners
1,Data Science Projects Best Practices
2,Mastering Building Scalable Cloud Applications...
3,Self-Taught Developer Roadmap Made Simple
4,Node.js Basics Deep Dive
5,Prompt Engineering Basics in Practice
6,Introduction to JavaScript Promises and Async/...
7,Advanced SQL Basics Guide
8,Understanding Database Indexing Explained
9,JavaScript ES6 Features From Scratch


In [54]:
recommend_video('Prompt Engineering Basics in Practice')

,video_id,title,category,channel,similarity_score
2618,V01915,Prompt Engineering Basics Explained with Examples,Generative AI,FutureTech Studio,0.894176
3490,V01843,Prompt Engineering Basics Best Practices,Generative AI,BranchOut Dev,0.849428
3374,V01957,Prompt Engineering Basics Crash Course,Generative AI,FutureTech Studio,0.848138
338,V01941,Prompt Engineering Basics Interview Questions,Generative AI,FutureTech Studio,0.844883
3468,V01847,Introduction to Prompt Engineering Basics,Generative AI,FutureTech Studio,0.831091


In [55]:
recommend_video('Node.js Basics Deep Dive')

,video_id,title,category,channel,similarity_score
4992,V03258,Mastering Node.js Basics in 2024,Node.js,PixelPerfect UX,0.953656
3307,V03239,Node.js Basics Crash Course,Node.js,PixelPerfect UX,0.943380
4243,V03269,Node.js Basics Tips and Tricks,Node.js,Quantum Coders,0.909328
3886,V03166,Node.js Basics for Absolute Beginners,Node.js,PixelPerfect UX,0.898846
3475,V03227,Node.js for Beginners Deep Dive,Node.js,PixelPerfect UX,0.897868


In [57]:
recommend_video('JavaScript ES6 Features From Scratch')

,video_id,title,category,channel,similarity_score
4552,V02892,JavaScript ES6 Features Quick Start Guide,JavaScript,GameLogic Studio,0.883700
1721,V02826,JavaScript ES6 Features Explained with Examples,JavaScript,ByteWise Learning,0.870812
4360,V02810,JavaScript ES6 Features Tutorial for Beginners,JavaScript,The Dev Journey,0.862469
1000,V02818,Understanding JavaScript ES6 Features,JavaScript,VisionaryAI,0.843727
805,V02853,JavaScript ES6 Features for Absolute Beginners,JavaScript,GameLogic Studio,0.843154


In [65]:
def search_video(query , n=10 , threshold=0.10):

  query_vector = tfidf.transform([query])

  similarity_scores = cosine_similarity(query_vector , tfidf_matrix).flatten()

  similarity_indices = similarity_scores.argsort()[::-1]

  top_indices = similarity_indices[:n]

  if similarity_scores[top_indices[0]] < threshold:
    print('Video does not exist')
    return

  recommendation = df.iloc[top_indices].copy()

  recommendation['similarity_score'] = similarity_scores[top_indices]

  return recommendation[
      ['video_id' , 'title' , 'category'  , 'channel' , 'similarity_score']
  ]

In [66]:
search_video('python tutorial')

,video_id,title,category,channel,similarity_score
1372,V00122,Python Variables Tips and Tricks,Python,WebCraft Studio,0.635864
3744,V00404,Complete Python Basics Tutorial,Python,Data Insights Studio,0.630017
3584,V00349,Python Basics Deep Dive,Python,CodeVerse,0.617751
4965,V00258,Complete Python Functions Tutorial,Python,WebCraft Studio,0.603917
3496,V00308,Understanding Python Loops,Python,ScriptSchool,0.600432
4091,V00222,Python Variables Full Course,Python,Data Insights Studio,0.597366
4332,V00149,Complete Python for Beginners Tutorial,Python,CodeVerse,0.591336
2909,V00098,Python for Beginners Made Simple,Python,Data Insights Studio,0.574036
2192,V00342,Python Functions for Absolute Beginners,Python,CodeVerse,0.567334
2346,V00242,Python Variables Real World Example,Python,WebCraft Studio,0.566216


In [67]:
search_video('machine learning full course')

,video_id,title,category,channel,similarity_score
2400,V01276,Machine Learning Basics Full Course,Machine Learning,SoundWave Studio,0.535558
2247,V01198,Machine Learning Pipelines Full Course,Machine Learning,SoundWave Studio,0.441958
2040,V01348,Data Preprocessing for Machine Learning Full C...,Machine Learning,SoundWave Studio,0.441071
989,V01078,Machine Learning Project Walkthrough Full Course,Machine Learning,SoundWave Studio,0.429244
2128,V00993,Machine Learning Project Walkthrough Crash Course,Machine Learning,SoundWave Studio,0.427815
1419,V01354,Complete Machine Learning Basics Tutorial,Machine Learning,CyberShield Academy,0.424427
858,V01154,Supervised Learning Full Course,Machine Learning,ScriptSchool,0.422232
816,V01043,Machine Learning Basics Crash Course,Machine Learning,CyberShield Academy,0.412887
3579,V01090,Feature Engineering Full Course,Machine Learning,ScriptSchool,0.402560
1553,V01262,Machine Learning Project Walkthrough Made Simple,Machine Learning,StackSmart Academy,0.386888


In [72]:
search_video('xkddnjdc scndsjvc ')

Video does not exist
